default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: postgres
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 10

development:
  <<: *default
  database: circle_test_failure_dev

test:
  <<: *default
  user: ubuntu
  database: circle_test_failure

other_database:
  <<: *default
  user: postgres
  database: other_database
  
production:
  <<: *default
  database: fake_production
  username: fakee
  password: 
